### ISSUE TITLE
question:阿里云只能添加中国大陆地区

### ISSUE THREAD

**Issue by lets-crazy** [DVKunion/SeaMoon#102]
**问题描述**
腾讯云可以支持全部地区，包括国外的。但是阿里云一旦选了国外的，就会有报错之类的 。这是就这样设计的吗？

**复现步骤**
1. 去除阿里云账户的其他地区，即可正常同步。
2. 添加阿里云所有地区（包括国外的），就会同步失败，直接500

**截图**

**其他信息**

+ Seamoon版本:
+ 系统类型(linux/windows/darwin):
+ 系统版本:
+ 运行模式(binary/docker):

**Comment by DVKunion** [comment]
有详细的复现步骤吗？暂时没遇到这个问题。

**Comment by DVKunion** [comment]
发现原因了。阿里云下掉了两个区域。导致在同步这两个区域的时候会出现问题。已同步最新区域。

**Comment by DVKunion** [comment]
fix v2.0.2
