### ISSUE TITLE
ERROR ProxyAddr Empty

### ISSUE THREAD

**Issue by yinqinghe** [DVKunion/SeaMoon#23]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/bcf46a37-90b2-4b4a-92f4-dbffa01a0bfa)
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/93af8411-a5c0-4655-95ef-cbaada164c92)

**Comment by DVKunion** [comment]
能在浏览器 localhost:7777 看一下配置信息吗？

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/a1be17ed-8228-4f1b-b141-cf8fc9ce025b)

**Comment by DVKunion** [comment]
带vpc的那个域名无法使用的，是属于阿里云内部网络访问的域名，不要填写，使用*.fcapp.run即可；然后需要加上协议头：ws://ws-node-seamoon-xxxxxxx.fcapp.run。

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/7b48cf8a-ff0e-4bbf-9aa8-eb5a3ba2e22f)

这又是什么问题？

**Comment by DVKunion** [comment]
服务端连接失败了，使用的是哪种函数部署的方式呢？

**Comment by yinqinghe** [comment]
阿里云的

**Comment by DVKunion** [comment]
试了一下，阿里云的go运行时好像还是1.18的版本，导致实际部署时候失败了(v1.2.0-beta.1升级go版本到了1.21)；可以看一下阿里云的控制台部署是否真实成功了；如果部署失败了的话那可能是这个bug问题，我一会修一下；也可以试一下降低一个版本使用v1.1.3的代码，相对会稳定些。

**Comment by yinqinghe** [comment]
https://seamoon.dvkunion.cn/guide/start/#%F0%9F%95%B9-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
根据这上面的文档做的，申请AK，SK，填入运行。
今天才部署阿里云应用，但没有成功
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/3596caa9-8f99-4fcb-9a17-d5aedea6c35f)

**Comment by DVKunion** [comment]
是的，日志显示了 go 版本为1.18 ，在 seamoon v1.2.0-beta 我尝试升级go版本到 1.21 了，看上去过于果断了而导致阿里云部署编译失败。文档还没有更新，仍停留在 v1.1.3 版本的文档。 

稍后我将修复这个问题，感谢反馈。 :)

**Comment by yinqinghe** [comment]
https://seamoon.dvkunion.cn/guide/start/#%F0%9F%95%B9-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
我就是按着这个文档做的，可以得到部署好的两个地址，还是运行bad handshake

 是需要按照这个文档再部署吗？https://seamoon.dvkunion.cn/guide/deploy/aliyun/#%E4%B8%89%E6%AD%A5%E9%83%A8%E7%BD%B2%E5%88%B0%E9%98%BF%E9%87%8C%E4%BA%91

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/cbf5677f-c35e-4117-8d26-839ad8b8a3ac)
这是1.1.3 client运行的打印输出

**Comment by DVKunion** [comment]
https://github.com/DVKunion/SeaMoon/pull/24 已修复。请删除 clone 的仓库和阿里云创建的应用，使用最新的代码重新按照阿里云的方式部署一次。最终要看到这个效果：

![image](https://github.com/DVKunion/SeaMoon/assets/42199853/9599d063-4ff2-4383-bee0-872204fbc5af)

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/dfd0e09b-85c3-49be-b8da-7475b9ba0b3d)
可以了，地址在那里看？

**Comment by DVKunion** [comment]
点击对应的资源信息，比如使用websocket的话点击ws-node进入详情页，“触发其管理（URL) " tag下：

![image](https://github.com/DVKunion/SeaMoon/assets/42199853/1295736e-3944-4610-a9db-d0913a93f394)

**Comment by yinqinghe** [comment]
还是bad handshake

**Comment by DVKunion** [comment]
客户端保证版本 v1.2.0-beta.1 , 地址协议填写正确并保存, 重启客户端试试。

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/b218a95c-e172-432f-bb3f-f408f2f05640)
这个zhen正常吗，很卡

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/e8e3c91e-9e87-4042-8e2e-b9fa6fc13500)

**Comment by DVKunion** [comment]
这个报错正常。现在没处理两边隧道其中一遍挥手后的动作，会导致关闭时的异常。

阿里云整体带宽并不高，加上默认s.yaml中配置是按照最低配置选的，因为便宜，基本上能满足正常流量需求。

推荐 sealos，更便宜且速率快。

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/819b5a6e-0a32-4590-a5fc-c0ce118eb97a)

![image](https://github.com/DVKunion/SeaMoon/assets/70678389/57e4079e-1cd1-4cc4-8272-6f1b7e296fb4)

**Comment by DVKunion** [comment]
版本刚更新 bug 有点多，sealos的手册也是1.1.3的，客户端得对应使用1.1.3 。

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/b82c4531-3971-4866-b530-31700f10bc4a)

**Comment by DVKunion** [comment]
<img width="234" alt="image" src="https://github.com/DVKunion/SeaMoon/assets/42199853/fcee6e6c-9b1c-4df1-8fba-41523bbb6022">
服务端用错镜像了。
![image](https://github.com/DVKunion/SeaMoon/assets/42199853/65ea906b-177e-4dd5-ad1a-f69d9f75902e)

**Comment by yinqinghe** [comment]
![image](https://github.com/DVKunion/SeaMoon/assets/70678389/9ec1e64f-8e4a-42da-91c3-b48f83d39632)
成功了

**Comment by DVKunion** [comment]
1.1.3 还是一个比较稳定的版本。1.2.0最近在做很多新功能支持，加上发版的是测试版本，可能问题比较多。再次感谢反馈。

**Comment by yinqinghe** [comment]
我可以理解成这就是个梯子吗？我看文档介绍是FaaS/BaaS 实现的 Serverless 云代理/渗透工具集，致力于开启云原生的渗透模式，我就没明白，云里雾里的

**Comment by DVKunion** [comment]
安全部分的应用层功能还没开出来，后续会开放很多安全相关的能力，比如无需服务器的反弹shell、动态的webshell隐匿等，不单单局限于网络层上的代理。但是网络层是整个的理论基础，有了这部分支持才能更好的玩一些新鲜的特性。

**Comment by DVKunion** [comment]
目前开出来的部分还仅仅是个代理 👀，可以关注下给个star接受第一时间的更新～

**Comment by yinqinghe** [comment]
好的，已star,期待新的功能开发出来
