### ISSUE TITLE
部署完，socks代理连接测试，不可用

### ISSUE THREAD

**Issue by Cedric1314** [DVKunion/SeaMoon#44]
云函数后台有日志请求

**Comment by DVKunion** [comment]
看一下请求日志的详情，还需要查看下本地客户端请求的日志报错信息。

**Comment by Cedric1314** [comment]
> 用的是哪种部署方式？看一下请求日志的详情，还需要查看下本地客户端请求的日志报错信息。

阿里云
![图片](https://github.com/DVKunion/SeaMoon/assets/42855430/ed2fb84f-a7af-4d2d-a34a-636e928afcbc)

![图片](https://github.com/DVKunion/SeaMoon/assets/42855430/02db7925-2471-4e08-8395-80127bea2e47)

**Comment by DVKunion** [comment]
看一下本地配置是否正确：代理地址需要是这样的格式： ws://ws-node-seamoon-xxxxxxx.fcapp.run 。

确认本地配置页面 配置的信息没有错误，执行 --version 看一下客户端版本号。需要与服务端版本号兼容。

一般来说，阿里云部署目前最新的版本为 v1.2.0-beta.1， 确认一下本地客户端版本是否为这个版本。看上去你这个客户端的日志截图不像是 v1.2.0-beta.1 的客户端日志样式。 试一下从release下载最新的客户端：https://github.com/DVKunion/SeaMoon/releases/tag/1.2.0-beta.1

**Comment by Cedric1314** [comment]
> 看一下本地配置是否正确：代理地址需要是这样的格式： ws://ws-node-seamoon-xxxxxxx.fcapp.run 。
> 
> 确认本地配置页面 配置的信息没有错误，执行 --version 看一下客户端版本号。需要与服务端版本号兼容。
> 
> 一般来说，阿里云部署目前最新的版本为 v1.2.0-beta.1， 确认一下本地客户端版本是否为这个版本。看上去你这个客户端的日志截图不像是 v1.2.0-beta.1 的客户端日志样式。 试一下从release下载最新的客户端：https://github.com/DVKunion/SeaMoon/releases/tag/1.2.0-beta.1
师傅，使用了1.2.0-beta.1版本调用还是存在问题
![图片](https://github.com/DVKunion/SeaMoon/assets/42855430/7065e579-7e01-49ff-af97-82cd4f20996f)

![图片](https://github.com/DVKunion/SeaMoon/assets/42855430/3bc22a67-b1fb-4647-b96a-afb3dca8ae89)
![图片](https://github.com/DVKunion/SeaMoon/assets/42855430/0d2ee28e-2078-45bf-aba4-027c060e08a4)
![图片](https://github.com/DVKunion/SeaMoon/assets/42855430/10197594-c950-4e37-a051-d97c3f1b3597)

**Comment by DVKunion** [comment]
> > 看一下本地配置是否正确：代理地址需要是这样的格式： ws://ws-node-seamoon-xxxxxxx.fcapp.run 。
> > 确认本地配置页面 配置的信息没有错误，执行 --version 看一下客户端版本号。需要与服务端版本号兼容。
> > 一般来说，阿里云部署目前最新的版本为 v1.2.0-beta.1， 确认一下本地客户端版本是否为这个版本。看上去你这个客户端的日志截图不像是 v1.2.0-beta.1 的客户端日志样式。 试一下从release下载最新的客户端：https://github.com/DVKunion/SeaMoon/releases/tag/1.2.0-beta.1
> > 师傅，使用了1.2.0-beta.1版本调用还是存在问题
> > ![图片](https://private-user-images.githubusercontent.com/42855430/298507360-7065e579-7e01-49ff-af97-82cd4f20996f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDczNjAtNzA2NWU1NzktN2UwMS00OWZmLWFmOTctODJjZDRmMjA5OTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmI3ZWIyODBiOTg2NGQ1NzA4NDBkZmE0Nzg5Yzc2YzAzOTU3YzM1MDY2ODMxYjE0ZDAwMjI1ZjFiOGEwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dluvblhn2qPcnXyb5ecwgomyvSMaxGoLxn45gwBAgCw)
> 
> ![图片](https://private-user-images.githubusercontent.com/42855430/298507431-3bc22a67-b1fb-4647-b96a-afb3dca8ae89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc0MzEtM2JjMjJhNjctYjFmYi00NjQ3LWI5NmEtYWZiM2RjYThhZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NzY5MzYwNzFlZTg2NWYzNmVhNjYwNjdhNDU1NjQ0NmQ1NjdmOWU2MWJhZGZiMWM4MTI4NDQzM2IwYTE3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5bg0kYU9fp3voWiE8nhrdDUbuhC0pHPy1BsDriPMPDw) ![图片](https://private-user-images.githubusercontent.com/42855430/298507714-0d2ee28e-2078-45bf-aba4-027c060e08a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc3MTQtMGQyZWUyOGUtMjA3OC00NWJmLWFiYTQtMDI3YzA2MGUwOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjg4MWFiOTZjYmZkNzliMWJlOWJlY2M5ZDI4YjMzM2FhY2MwYmY5M2RjYjg4Y2QyNzQwNjRlYzhiYWRhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q-sV_p3yZDFe_325__6GX6LMySNqkqqa_4nA57WmOCI) ![图片](https://private-user-images.githubusercontent.com/42855430/298507867-10197594-c950-4e37-a051-d97c3f1b3597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc4NjctMTAxOTc1OTQtYzk1MC00ZTM3LWEwNTEtZDk3YzNmMWIzNTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZjQ3Mzc1ZTU3NWJjMmZkNWJmZmRmMzcyMmU3OGNhYmQxZTg5ZGVmNzJjZjE3NjM4ZDExMTY1N2MyYWI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-INBASs6R24A-OeT92hSTpUUfalFLyp5lsEn4pwFD8)

这个不是显示 socks 代理已经通了吗，延迟显示已经出来了我看？`read/write on close pipe ` 这个报错的内容目前是预期，在这个beta.1版本没有处理这个 io.reset 的问题。配合浏览器插件使用这个代理端口理论来讲应该是已经可以使用了的。

**Comment by Cedric1314** [comment]
> > > 看一下本地配置是否正确：代理地址需要是这样的格式： ws://ws-node-seamoon-xxxxxxx.fcapp.run 。
> > > 确认本地配置页面 配置的信息没有错误，执行 --version 看一下客户端版本号。需要与服务端版本号兼容。
> > > 一般来说，阿里云部署目前最新的版本为 v1.2.0-beta.1， 确认一下本地客户端版本是否为这个版本。看上去你这个客户端的日志截图不像是 v1.2.0-beta.1 的客户端日志样式。 试一下从release下载最新的客户端：https://github.com/DVKunion/SeaMoon/releases/tag/1.2.0-beta.1
> > > 师傅，使用了1.2.0-beta.1版本调用还是存在问题
> > > ![图片](https://private-user-images.githubusercontent.com/42855430/298507360-7065e579-7e01-49ff-af97-82cd4f20996f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDczNjAtNzA2NWU1NzktN2UwMS00OWZmLWFmOTctODJjZDRmMjA5OTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmI3ZWIyODBiOTg2NGQ1NzA4NDBkZmE0Nzg5Yzc2YzAzOTU3YzM1MDY2ODMxYjE0ZDAwMjI1ZjFiOGEwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dluvblhn2qPcnXyb5ecwgomyvSMaxGoLxn45gwBAgCw)
> > 
> > 
> > ![图片](https://private-user-images.githubusercontent.com/42855430/298507431-3bc22a67-b1fb-4647-b96a-afb3dca8ae89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc0MzEtM2JjMjJhNjctYjFmYi00NjQ3LWI5NmEtYWZiM2RjYThhZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NzY5MzYwNzFlZTg2NWYzNmVhNjYwNjdhNDU1NjQ0NmQ1NjdmOWU2MWJhZGZiMWM4MTI4NDQzM2IwYTE3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5bg0kYU9fp3voWiE8nhrdDUbuhC0pHPy1BsDriPMPDw) ![图片](https://private-user-images.githubusercontent.com/42855430/298507714-0d2ee28e-2078-45bf-aba4-027c060e08a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc3MTQtMGQyZWUyOGUtMjA3OC00NWJmLWFiYTQtMDI3YzA2MGUwOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjg4MWFiOTZjYmZkNzliMWJlOWJlY2M5ZDI4YjMzM2FhY2MwYmY5M2RjYjg4Y2QyNzQwNjRlYzhiYWRhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q-sV_p3yZDFe_325__6GX6LMySNqkqqa_4nA57WmOCI) ![图片](https://private-user-images.githubusercontent.com/42855430/298507867-10197594-c950-4e37-a051-d97c3f1b3597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc4NjctMTAxOTc1OTQtYzk1MC00ZTM3LWEwNTEtZDk3YzNmMWIzNTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZjQ3Mzc1ZTU3NWJjMmZkNWJmZmRmMzcyMmU3OGNhYmQxZTg5ZGVmNzJjZjE3NjM4ZDExMTY1N2MyYWI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-INBASs6R24A-OeT92hSTpUUfalFLyp5lsEn4pwFD8)
> 
> 这个不是显示 socks 代理已经通了吗，延迟显示已经出来了我看？`read/write on close pipe ` 这个报错的内容目前是预期，在这个beta.1版本没有处理这个 io.reset 的问题。配合浏览器插件使用这个代理端口理论来讲应该是已经可以使用了的。

![图片](https://github.com/DVKunion/SeaMoon/assets/42855430/a2c85973-43b8-4f9f-a00b-ee00ee91b04f)
谢谢师傅，因该是代理有点卡，访问网页比较慢，很卡。。

**Comment by DVKunion** [comment]
> > > > 看一下本地配置是否正确：代理地址需要是这样的格式： ws://ws-node-seamoon-xxxxxxx.fcapp.run 。
> > > > 确认本地配置页面 配置的信息没有错误，执行 --version 看一下客户端版本号。需要与服务端版本号兼容。
> > > > 一般来说，阿里云部署目前最新的版本为 v1.2.0-beta.1， 确认一下本地客户端版本是否为这个版本。看上去你这个客户端的日志截图不像是 v1.2.0-beta.1 的客户端日志样式。 试一下从release下载最新的客户端：https://github.com/DVKunion/SeaMoon/releases/tag/1.2.0-beta.1
> > > > 师傅，使用了1.2.0-beta.1版本调用还是存在问题
> > > > ![图片](https://private-user-images.githubusercontent.com/42855430/298507360-7065e579-7e01-49ff-af97-82cd4f20996f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDczNjAtNzA2NWU1NzktN2UwMS00OWZmLWFmOTctODJjZDRmMjA5OTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmI3ZWIyODBiOTg2NGQ1NzA4NDBkZmE0Nzg5Yzc2YzAzOTU3YzM1MDY2ODMxYjE0ZDAwMjI1ZjFiOGEwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dluvblhn2qPcnXyb5ecwgomyvSMaxGoLxn45gwBAgCw)
> > > 
> > > 
> > > ![图片](https://private-user-images.githubusercontent.com/42855430/298507431-3bc22a67-b1fb-4647-b96a-afb3dca8ae89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc0MzEtM2JjMjJhNjctYjFmYi00NjQ3LWI5NmEtYWZiM2RjYThhZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NzY5MzYwNzFlZTg2NWYzNmVhNjYwNjdhNDU1NjQ0NmQ1NjdmOWU2MWJhZGZiMWM4MTI4NDQzM2IwYTE3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5bg0kYU9fp3voWiE8nhrdDUbuhC0pHPy1BsDriPMPDw) ![图片](https://private-user-images.githubusercontent.com/42855430/298507714-0d2ee28e-2078-45bf-aba4-027c060e08a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc3MTQtMGQyZWUyOGUtMjA3OC00NWJmLWFiYTQtMDI3YzA2MGUwOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjg4MWFiOTZjYmZkNzliMWJlOWJlY2M5ZDI4YjMzM2FhY2MwYmY5M2RjYjg4Y2QyNzQwNjRlYzhiYWRhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q-sV_p3yZDFe_325__6GX6LMySNqkqqa_4nA57WmOCI) ![图片](https://private-user-images.githubusercontent.com/42855430/298507867-10197594-c950-4e37-a051-d97c3f1b3597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE1NTksIm5iZiI6MTcwNTkxMTI1OSwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MDc4NjctMTAxOTc1OTQtYzk1MC00ZTM3LWEwNTEtZDk3YzNmMWIzNTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZjQ3Mzc1ZTU3NWJjMmZkNWJmZmRmMzcyMmU3OGNhYmQxZTg5ZGVmNzJjZjE3NjM4ZDExMTY1N2MyYWI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-INBASs6R24A-OeT92hSTpUUfalFLyp5lsEn4pwFD8)
> > 
> > 
> > 这个不是显示 socks 代理已经通了吗，延迟显示已经出来了我看？`read/write on close pipe ` 这个报错的内容目前是预期，在这个beta.1版本没有处理这个 io.reset 的问题。配合浏览器插件使用这个代理端口理论来讲应该是已经可以使用了的。
> 
> ![图片](https://private-user-images.githubusercontent.com/42855430/298520450-a2c85973-43b8-4f9f-a00b-ee00ee91b04f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTQwOTgsIm5iZiI6MTcwNTkxMzc5OCwicGF0aCI6Ii80Mjg1NTQzMC8yOTg1MjA0NTAtYTJjODU5NzMtNDNiOC00ZjlmLWEwMGItZWUwMGVlOTFiMDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4NTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjM2Y4MzgyNWVmMGJmOGYyODJjZGUxOGZiMGNhOGY1MDNkNjdmZjFiZGVjNjU3MDk0NzM4YzRiM2EwNWMyOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VcBcDvaY6GbQfetZyff_Z_Ryw2qw2aKWy2dKpVHak50) 谢谢师傅，因该是代理有点卡，访问网页比较慢，很卡。。

阿里云确实是这个尿性，想要更好的体验需要升级cpu/内存配置。推荐使用sealos部署方案，速度更快，价格更低。

**Comment by DVKunion** [comment]
没什么问题的话这个 Issue 我就 close 掉了～
