### ISSUE TITLE
sealos部署后 服务不可用

### ISSUE THREAD

**Issue by u21h2** [DVKunion/SeaMoon#54]
用wss和grpc都试了下

wss:
[Socks5] WebSocket Upgrade error: tls: failed to verify certificate: x509: certificate signed by unknown authority

![image](https://github.com/DVKunion/SeaMoon/assets/24861470/944e41c1-bf47-40e1-a5cd-b631d2a40d14)
<img width="1060" alt="image" src="https://github.com/DVKunion/SeaMoon/assets/24861470/dab79b47-4631-4ae4-86c5-e6f75d8e220b">

grpc:
ERRO[0000] ProxyAddr Empty, Please Check Your Config File

![image](https://github.com/DVKunion/SeaMoon/assets/24861470/f5171b11-aab4-43c8-aa9c-1b38b612c3b6)
<img width="641" alt="image" src="https://github.com/DVKunion/SeaMoon/assets/24861470/4e64943e-6435-435a-9a6c-bdc38c56e3bd">

macos上docker启动的命令: docker run -it -d -p 7777:7777 -p 1080:1080 dvkunion/seamoon-client
每次修改配置后都有重启docker

**Comment by u21h2** [comment]
是因为我docker镜像太旧了吗 看了下是六个月前的版本 
<img width="773" alt="image" src="https://github.com/DVKunion/SeaMoon/assets/24861470/80091cd8-58c1-4a0e-8ce6-ebf0939541a1">
我从release里下个试试

**Comment by DVKunion** [comment]
`docker run -it -d --net=host dvkunion/seamoon:latest proxy` 

<img width="956" alt="image" src="https://github.com/DVKunion/SeaMoon/assets/42199853/b5791aa5-6cae-4f7b-b12b-64f1dd6c49dd">

在哪里看到的手册用的是 client 呢？可能手册更新漏掉了，

**Comment by u21h2** [comment]
https://seamoon.dvkunion.cn/guide/deploy/sealos/#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2

**Comment by DVKunion** [comment]
看上去是漏掉了。我记一下，下次一起更新上去。感谢反馈 :)

**Comment by u21h2** [comment]
还有个问题 s.yml 版本没改

actions:
  pre-deploy:
    - run: wget https://github.com/DVKunion/SeaMoon/releases/download/1.2.0-beta.2/SeaMoon_1.2.0-beta.2_linux_amd64.tar.gz
      path: ./
    - run: tar -zvxf SeaMoon_1.2.0-beta.1_linux_amd64.tar.gz 这里没改
      path: ./
    - run: chmod +x seamoon
      path: ./

**Comment by DVKunion** [comment]
fix at #56 ，再次感谢师傅的反馈，后续若有任何其他问题欢迎提交 :>
