### ISSUE TITLE
客户端部署后找不到账号密码

### ISSUE THREAD

**Issue by feeops** [DVKunion/SeaMoon#81]
docker run -it -d --net=host dvkunion/seamoon:latest proxy

要填账号密码，文档中没有写默认账号密码

**Comment by DVKunion** [comment]
2.0版本正在更新中，手册这周左右会同步更新，目前latest镜像被替换为了2.0版本。

如果正在使用，请手动指定老版本镜像：dvkunion/seamoon:1.2.0-beta.2

如果你希望尝试体验使用新版本，默认的账户密码为： seamoon/seamoon
