### ISSUE TITLE
Sealos认证错误

### ISSUE THREAD

**Issue by ymbzd** [DVKunion/SeaMoon#88]
![image](https://github.com/DVKunion/SeaMoon/assets/39881690/b133e6e1-7a86-45ea-a9ff-8200d4617e0e)
认证信息是直接复制过来的   但是同步不到

**Comment by DVKunion** [comment]
试了一下，我这边没有什么问题，没出现这个`user is not found` , 不过你可以按照下面的步骤排查：
- [ ] 确认配置的账户所选区域和复制的凭证区域在一个区，如：新加坡区，不要复制成北京区的凭证。
- [ ] 确认复制的凭证是正确的，可以尝试粘贴到文本中，检查复制的内容是否为`apiVersion`开头的yaml文件。
- [ ] 确认网络可以访问sealos的服务。

**Comment by ymbzd** [comment]
感谢指正…地区和凭证没在一个地方
