### ISSUE TITLE
SeaMon Client

### ISSUE THREAD

**Issue by maomaojzb** [DVKunion/SeaMoon#93]
**问题描述**
SeaMon Client Web并未找到关于说明文档中此项设置
![image](https://github.com/DVKunion/SeaMoon/assets/49849937/2c5b4323-44c6-4fa5-9138-8d12a17ca689)

部署方式：PaaS
平台：sealos
Sealos Cloud应用管理已设置，设置步骤参考：https://seamoon.dvkunion.cn/guide/paas/
应用管理平台：已启动
代理方式：WebSock

SeaMon Client启动命令：
seamoon.exe client
本地截图：
![image](https://github.com/DVKunion/SeaMoon/assets/49849937/a5ad3e03-478c-40b3-a41d-a85922be6197)

无下方设置
![image](https://github.com/DVKunion/SeaMoon/assets/49849937/b266f59a-1791-4845-86f0-0a9215e7cfc6)

**复现步骤**

**截图**

**其他信息**

+ Seamoon版本:
+ 系统类型(linux/windows/darwin):
+ 系统版本:
+ 运行模式(binary/docker):

**Comment by DVKunion** [comment]
这是两个不同版本的东西了；新版本只需要在web控制端操作就行。

**Comment by DVKunion** [comment]
看一下最新的手册。不要看老版本的了。

**Comment by maomaojzb** [comment]
Ths.
