### ISSUE TITLE
添加腾讯云导致崩溃

### ISSUE THREAD

**Issue by defidead** [DVKunion/SeaMoon#98]
**注意**
- [ ] 我确定已经认真的阅读了手册。
- [ ] 我确信这是一个BUG，而不是由于个人配置和错误的使用导致的。

**问题描述**

**如何复现**
复现步骤如下:
1. 添加腾讯云账号
2. 程序崩溃
3. xxxxxx
4. xxxxxxx

**预期的结果**

**截图**
注意隐私信息

**其他信息**
+ Seamoon版本:
+ 系统类型(linux/windows/darwin):linux/windows
+ 系统版本:
+ 运行模式(binary/docker): linux(docker) windows (binary)

**Additional context**

**Comment by DVKunion** [comment]
能否提供崩溃的panic日志？

**Comment by defidead** [comment]
![image](https://github.com/user-attachments/assets/0387316f-eb03-448e-8257-2ed7c3369951)

**Comment by DVKunion** [comment]
看来确实是个bug，可能你的账户没有开对应的区域，对应的代码没考虑这个case，空指针了。有空修一下。

**Comment by defidead** [comment]
账号应该是开通了对应地区的，，，我腾讯云控制台还能看见之前的函数
![image](https://github.com/user-attachments/assets/8ce93ed4-8465-4aa9-9258-9ce7d8de8136)

**Comment by DVKunion** [comment]
这个堆栈展示的内容少了一些。。。能手动在 seamoon 管理端点击这个腾讯云账户，然后点击手动同步试一下吗？然后再看一下报错。

**Comment by defidead** [comment]
![image](https://github.com/user-attachments/assets/412214dd-2a97-4b70-93f4-59df03ab1060)
。。。。同步不了

**Comment by DVKunion** [comment]
这个是点击的更新还是点击的 “从云端更新函数数据“ ？

**Comment by defidead** [comment]
从云端更新函数，更新也是这个样子
![image](https://github.com/user-attachments/assets/d295e7e7-54d3-44e1-984d-9209070d81e1)

**Comment by DVKunion** [comment]
可以发我一下邮箱吧，我测一下看看具体问题是哪里。

**Comment by DVKunion** [comment]
测试了一下。。。我这边是正常的，没复现出来。
<img width="576" alt="image" src="https://github.com/user-attachments/assets/c404a5b4-633a-47f5-8b24-2bcfd84e76c1">
