### ISSUE TITLE
bug: 无法建立代理

### ISSUE THREAD

**Issue by defidead** [DVKunion/SeaMoon#99]
**注意**
- [ ] 我确定已经认真的阅读了手册。
- [ ] 我确信这是一个BUG，而不是由于个人配置和错误的使用导致的。

**问题描述**
阿里云建立云函数后功能不正常

**如何复现**
复现步骤如下:
1. 新增云函数
2. xxxxxx
3. xxxxxx
4. xxxxxxx

**预期的结果**
无法使用
**截图**
注意隐私信息
![image](https://github.com/user-attachments/assets/a5eaae1c-e178-4759-88ed-c067b754a944)
![image](https://github.com/user-attachments/assets/cd4994ff-7264-4de1-bb5f-841413ecf5a2)

**其他信息**
+ Seamoon版本:
+ 系统类型(linux/windows/darwin):windows
+ 系统版本:
+ 运行模式(binary/docker):binary

**Additional context**

**Comment by DVKunion** [comment]
登录一下fc控制台，看看是否有对应的函数创建成功。从日志上来看，你的客户端无法访问到函数的域名；或是对应关联的函数存在异常。

**Comment by defidead** [comment]
![image](https://github.com/user-attachments/assets/09c01ed6-0c71-466b-a4ad-65f86cd143e1)
函数是创建成功了

**Comment by DVKunion** [comment]
看着你是创建了一个 auto 的代理服务，然后通过client在请求函数；auto目前仅支持 http / socks5 ；而且没有详细的测试，可以尝试一下创建个 其他协议的或者是创建好的函数直接一键导入clash客户端使用？

**Comment by defidead** [comment]
神医！导入clsh可以了
